[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://weaveos.onrender.com/api"
  VITE_NODE_ENV = "production"
  VITE_ENABLE_DEBUG = "false"

# Production context (for main branch)
[context.production.environment]
  VITE_API_BASE_URL = "https://weaveos.onrender.com/api"
  VITE_NODE_ENV = "production"

# Deploy preview context (for pull requests)
[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://weaveos.onrender.com/api"
  VITE_NODE_ENV = "staging"

# Branch deploy context (for other branches)
[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://weaveos.onrender.com/api"
  VITE_NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
