version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: weave-os-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: weave123
      MONGO_INITDB_DATABASE: weave-os
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - weave-network

  backend:
    build: .
    container_name: weave-os-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:weave123@mongodb:27017/weave-os?authSource=admin
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - weave-network

volumes:
  mongodb_data:

networks:
  weave-network:
    driver: bridge
